spring:
  datasource:
    url: jdbc:mysql://localhost:3306/donkeyDatabase
    username: root
    password: '0000'
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  output:
    ansi:
      enabled: always